# Change these first
owner: FxllenCode # Your GitHub username
repo: HWHelpNowStatus # Your GitHub repository name
# e
# Add your sites here
sites:
  - name: Homework Help Now
    url: https://hwhelpnow.com/
  - name: Zoho SalesIQ (Live-Chat)
    url: https://www.zoho.com/salesiq/
  - name: Firebase Hosting
    url: https://firebase.google.com/

status-website:

  # Uncomment the following line if you don't have a custom domain and add your repo name
  cname: status.hwhelpnow.com
  name: Homework Help Now Status
  introTitle: "**Homework Help Now's** official status page."
  introMessage: This is the status page for [Homework Help Now.](https://hwhelpnow.com) Here you can see if there are any issues with the site, or it's endpoints.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/FxllenCode/HWHelpNow
    - title: Main Site
      href: https://hwhelpnow.com/

  logoUrl: https://hwhelpnow.com/Homework%20Help%20Now%20Logo%20(2).png


 assignees:
  - FxllenCode

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
