# Change these first
owner: FxllenCode # Your GitHub username
repo: FxllenCode/HWHelpNowStatus # Your GitHub repository name

# Add your sites here
sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Broken Site
    url: https://thissitedoesnotexist.com
  - name: Secret Site
    url: $SECRET_SITE

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.hwhelpnow.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Homework Help Now Status
  introTitle: "This is the official status page for hwhelpnow.com"
  introMessage: This is a test
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/FxllenCode/HWHelpNow

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
