# Change these first
owner: FxllenCode # Your GitHub username
repo: HWHelpNowStatus # Your GitHub repository name
# e
# Add your sites here
sites:
  - name: Homework Help Now
    url: https://hwhelpnow.com/
  - name: Zoho SalesIQ (Live-Chat)
    url: https://www.zoho.com/salesiq/
  - name: Firebase Hosting
    url: https://firebase.google.com/

status-website:

  # Uncomment the following line if you don't have a custom domain and add your repo name
  cname: status.hwhelpnow.com
  name: Homework Help Now Status
  introTitle: "This is the official status page for hwhelpnow.com"
  introMessage: This is a test
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/FxllenCode/HWHelpNow

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
